plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
baseurl: ""
url: "https://leohmcs.github.io/avantufmg.github.io/"
show_downloads: false
google_analytics: false
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
